### ISSUE TITLE
Should configure~ be checked in?

### ISSUE THREAD

**Issue by trondtynnol** [giellalt/lang-mns#1]
After compiling I noticed the apparently temporary file configure~ is checked in. I figure that this file is generated from configure.ac anyways, so I would guess that it is checked in by mistake. Should it be removed?

**Comment by flammie** [comment]
shoud be deleted, I think if it isn't in .gitignore it's because most people have it (or `*~`) in user-configured gitignore in $HOME cause it's so common backup suffix.

**Comment by trondtynnol** [comment]
All right. I see it is actually in .gitignore as well.
